-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 01:57:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema QLSinhVien
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `QLSinhVien` ;

-- -----------------------------------------------------
-- Schema QLSinhVien
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QLSinhVien` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `QLSinhVien` ;

-- -----------------------------------------------------
-- Table `LopHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LopHoc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `LopHoc` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `MaLop` VARCHAR(8) NOT NULL,
  `TenLop` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SinhVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SinhVien` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SinhVien` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `MSSV` VARCHAR(16) NOT NULL,
  `HoTen` NVARCHAR(45) NOT NULL,
  `GioiTinh` INT NULL,
  `CMND` VARCHAR(45) NOT NULL,
  `LopHocId` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CMND_UNIQUE` ON `SinhVien` (`CMND` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `MSSV_UNIQUE` ON `SinhVien` (`MSSV` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MonHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MonHoc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MonHoc` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `MaMon` VARCHAR(8) NOT NULL,
  `TenMon` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HocKy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HocKy` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HocKy` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TenHocKy` NVARCHAR(45) NOT NULL,
  `TuNgay` DATE NOT NULL,
  `DenNgay` DATE NOT NULL,
  `NienKhoa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HocKy_MonHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HocKy_MonHoc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HocKy_MonHoc` (
  `HocKyId` INT NULL,
  `MonHocId` INT NULL,
  `PhongHoc` VARCHAR(8) NULL,
  `Id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HocKyMonHoc_has_SinhVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HocKyMonHoc_has_SinhVien` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HocKyMonHoc_has_SinhVien` (
  `HocKy_MonHoc_Id` INT NOT NULL,
  `SinhVienId` INT NOT NULL,
  `DiemGK` FLOAT NULL,
  `DiemCK` FLOAT NULL,
  `DiemKhac` FLOAT NULL,
  `DiemTong` FLOAT NULL,
  PRIMARY KEY (`HocKy_MonHoc_Id`, `SinhVienId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `LopHoc_has_HocKyMonHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LopHoc_has_HocKyMonHoc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `LopHoc_has_HocKyMonHoc` (
  `LopHocId` INT NOT NULL,
  `HocKy_MonHoc_Id` INT NOT NULL,
  PRIMARY KEY (`HocKy_MonHoc_Id`, `LopHocId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PhucKhao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PhucKhao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PhucKhao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TuNgay` DATE NULL,
  `DenNgay` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SinhVien_has_PhucKhao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SinhVien_has_PhucKhao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SinhVien_has_PhucKhao` (
  `SinhVienId` INT NOT NULL,
  `PhucKhaoId` INT NOT NULL,
  `HocKy_MonHoc_Id` INT NOT NULL,
  `DiemMongMuon` FLOAT NULL,
  `LyDo` NVARCHAR(512) NULL,
  PRIMARY KEY (`SinhVienId`, `PhucKhaoId`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
